USE [master]
GO

/****** Object:  Database [NORTHWIND3]    Script Date: 6/21/2021 3:20:26 PM ******/
CREATE DATABASE [NORTHWIND3]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Northwind', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\NORTHWIND3.MDF' , SIZE = 4672KB , MAXSIZE = UNLIMITED, FILEGROWTH = 80KB )
 LOG ON 
( NAME = N'Northwind_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\NORTHWIND3_log.ldf' , SIZE = 3840KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [NORTHWIND3].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO

ALTER DATABASE [NORTHWIND3] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [NORTHWIND3] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [NORTHWIND3] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [NORTHWIND3] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [NORTHWIND3] SET ARITHABORT OFF 
GO

ALTER DATABASE [NORTHWIND3] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [NORTHWIND3] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [NORTHWIND3] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [NORTHWIND3] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [NORTHWIND3] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [NORTHWIND3] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [NORTHWIND3] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [NORTHWIND3] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [NORTHWIND3] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [NORTHWIND3] SET  DISABLE_BROKER 
GO

ALTER DATABASE [NORTHWIND3] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [NORTHWIND3] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [NORTHWIND3] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [NORTHWIND3] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [NORTHWIND3] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [NORTHWIND3] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [NORTHWIND3] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [NORTHWIND3] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [NORTHWIND3] SET  MULTI_USER 
GO

ALTER DATABASE [NORTHWIND3] SET PAGE_VERIFY TORN_PAGE_DETECTION  
GO

ALTER DATABASE [NORTHWIND3] SET DB_CHAINING OFF 
GO

ALTER DATABASE [NORTHWIND3] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [NORTHWIND3] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [NORTHWIND3] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [NORTHWIND3] SET QUERY_STORE = OFF
GO

USE [NORTHWIND3]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
